### PR TITLE
Add onChange event to input to listen to clearing changes

### PR DESCRIPTION
**Pull request by Roscode**
- MAIN-20873

sandbox: main-20873.vpc.clypd.com:3000

### CODE REVIEW

**Comment by benjamincudi** [comment]
Just for my own understanding, I assume that your changes were only to `src/ReactPikadayComponent.js`, and the other changes are a result of running `npm run build`?

**Comment by Roscode** [comment]
@benjamincudi that is correct

**Comment by benjamincudi** [comment]
👍  LGTM then
Idle thought, we should schedule a ticket or two to clean this up and add some tests. I'm curious about the reason for `index.js`, might have to do some research

**Comment by Roscode** [comment]
@benjamincudi I agree, it was a very frustrating process to go through all the steps to update this dependency then while testing on localhost realizing that the code hadn't changed _at all_ and being like "what the actual what" until realizing the repo had to contain the build artifacts 😞

**Comment by Roscode** [comment]
also for posterity I'm gonna merge this now, it's two lines of actual change so I think one reviewer is enough especially one familiar with the code

**Comment by davidclypd** [comment]
I want to believe I sent an email about this repo and how to rebuild it but it's entirely possible that I didn't

**Pull request merged**
