### PR TITLE
only set the date after changing min and max date

### PR DESCRIPTION
**Pull request by davidclypd**
- this was causing a bug where new dates would be set, but the main date was still constrained by the old min/max dates

### CODE REVIEW

**Comment by benjamincudi** [comment]
I think we might need to commit the compiled version as well, you should be able to `npm install && npm run build`

**Comment by davidclypd** [comment]
@KrisNi look good?

**Comment by benjamincudi** [comment]
The extra changes that showed up in the build are a little odd, but nothing seems alarming there

**Comment by davidclypd** [comment]
yeah, not sure why. All I did was install + build

**Pull request merged**
